routes/web.php
<?php

use App\Http\Controllers\Admin\CanteenController;
use App\Http\Controllers\Admin\ClientController;
use App\Http\Controllers\Admin\FoodController;
use App\Http\Controllers\AdminCanteen\OverviewController;
use App\Http\Controllers\AdminCanteen\ProductController;
use App\Http\Controllers\AdminCanteen\ReportController;
use App\Http\Controllers\Superadmin\AdminController;
use App\Http\Controllers\Superadmin\CanteenController as SuperadminCanteenController;
use App\Http\Controllers\Superadmin\CategoryController;
use App\Http\Controllers\Superadmin\ClientController as SuperadminClientController;
use App\Http\Controllers\Superadmin\DashboardController;
use App\Http\Controllers\Superadmin\ParkingSpotController;
use App\Http\Controllers\Superadmin\SmartCanteenController;
use App\Http\Controllers\Superadmin\SmartParkingController;
use App\Http\Controllers\Superadmin\StudentController;
use App\Http\Controllers\Auth\AuthController;

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/', [AuthController::class, 'index']);
Route::get('/login', [AuthController::class, 'index'])->name('login');
Route::post('/login', [AuthController::class, 'store']);
Route::post('/logout', [AuthController::class, 'logout'])->name('logout');

Route::group(['middleware' => ['checkrole:admincanteen']], function () {
    Route::prefix('admin-canteen')->name('admin_canteen.')->group(function () {
        Route::prefix('overview')->name('overview.')->group(function () {
            Route::get('', [OverviewController::class, 'index'])->name('index');
            Route::put('status-canteen', [OverviewController::class, 'statusCanteen'])->name('status_canteen');
        });

        Route::prefix('report')->name('report.')->group(function () {
            Route::get('', [ReportController::class, 'index'])->name('index');
            Route::get('show/{id}', [ReportController::class, 'show'])->name('show');
            Route::get('getPager', [ReportController::class, 'getpager'])->name('get_pager');
            Route::put('updatePager', [ReportController::class, 'updatePager'])->name('update_pager');
            Route::put('updateTaken', [ReportController::class, 'updateTaken'])->name('update_taken');
            Route::put('updateNotif', [ReportController::class, 'updateNotif'])->name('update_notif');
            Route::delete('delete', [ReportController::class, 'delete'])->name('delete');
            // Route::get('cetak-nota/{id}', [ReportController::class, 'print'])->name('print');
        });
        Route::prefix('product')->name('product.')->group(function () {
            Route::get('', [ProductController::class, 'index'])->name('index');
            Route::get('create', [ProductController::class, 'create'])->name('create');
            Route::get('{id}/edit', [ProductController::class, 'edit'])->name('edit');
            Route::post('store', [ProductController::class, 'store'])->name('store');
            Route::get('{id}/edit', [ProductController::class, 'edit'])->name('edit');
            Route::put('update', [ProductController::class, 'update'])->name('update');
            Route::delete('delete', [ProductController::class, 'delete'])->name('delete');
        });
    });
});

//Superadmin
Route::group(['middleware' => ['checkrole:superadmin', 'web']], function () {
    Route::prefix('superadmin')->name('superadmin.')->group(function () {
        Route::prefix('dashboard')->name('dashboard.')->group(function () {
            Route::get('', [DashboardController::class, 'index'])->name('index');
        });

        Route::prefix('admin')->name('admin.')->group(function () {
            Route::get('', [AdminController::class, 'index'])->name('index');
            Route::get('create', [AdminController::class, 'create'])->name('create');
            Route::post('store', [AdminController::class, 'store'])->name('store');
            Route::get('{id}/edit', [AdminController::class, 'edit'])->name('edit');
            Route::put('update', [AdminController::class, 'update'])->name('update');
            Route::delete('delete', [AdminController::class, 'delete'])->name('delete');
        });
        Route::prefix('category')->name('category.')->group(function () {
            Route::get('', [CategoryController::class, 'index'])->name('index');
            Route::get('create', [CategoryController::class, 'create'])->name('create');
            Route::post('store', [CategoryController::class, 'store'])->name('store');
            Route::get('{id}/edit', [CategoryController::class, 'edit'])->name('edit');
            Route::put('update', [CategoryController::class, 'update'])->name('update');
            Route::delete('delete', [CategoryController::class, 'delete'])->name('delete');
        });
        Route::prefix('parking-spot')->name('parking_spot.')->group(function () {
            Route::get('', [ParkingSpotController::class, 'index'])->name('index');
            Route::get('create', [ParkingSpotController::class, 'create'])->name('create');
            Route::post('store', [ParkingSpotController::class, 'store'])->name('store');
            Route::get('{id}/edit', [ParkingSpotController::class, 'edit'])->name('edit');
            Route::put('update', [ParkingSpotController::class, 'update'])->name('update');
            Route::delete('delete', [ParkingSpotController::class, 'delete'])->name('delete');
        });
        Route::prefix('client')->name('client.')->group(function () {
            Route::get('', [SuperadminClientController::class, 'index'])->name('index');
            Route::get('blank', [SuperadminClientController::class, 'blank'])->name('blank');
            Route::get('create', [SuperadminClientController::class, 'create'])->name('create');
            Route::post('store', [SuperadminClientController::class, 'store'])->name('store');
            Route::get('{id}/edit', [SuperadminClientController::class, 'edit'])->name('edit');
            Route::put('update', [SuperadminClientController::class, 'update'])->name('update');
            Route::delete('delete', [SuperadminClientController::class, 'delete'])->name('delete');
        });
        Route::prefix('canteen')->name('canteen.')->group(function () {
            Route::get('', [SuperadminCanteenController::class, 'index'])->name('index');
            Route::get('create', [SuperadminCanteenController::class, 'create'])->name('create');
            Route::post('store', [SuperadminCanteenController::class, 'store'])->name('store');
            Route::get('{id}/edit', [SuperadminCanteenController::class, 'edit'])->name('edit');
            Route::put('update', [SuperadminCanteenController::class, 'update'])->name('update');
            Route::delete('delete', [SuperadminCanteenController::class, 'delete'])->name('delete');
        });

        Route::prefix('user')->name('student.')->group(function () {
            Route::get('', [StudentController::class, 'index'])->name('index');
            Route::get('create', [StudentController::class, 'create'])->name('create');
            Route::post('store', [StudentController::class, 'store'])->name('store');
            Route::get('{id}/edit', [StudentController::class, 'edit'])->name('edit');
            Route::put('update', [StudentController::class, 'update'])->name('update');
            Route::delete('delete', [StudentController::class, 'delete'])->name('delete');
        });

        Route::prefix('smart-canteen')->name('smart_canteen.')->group(function () {
            Route::get('', [SmartCanteenController::class, 'index'])->name('index');
        });
        Route::prefix('smart-parking')->name('smart_parking.')->group(function () {
            Route::get('', [SmartParkingController::class, 'index'])->name('index');
        });
    });
});

app/Models/ParkingSpot.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ParkingSpot extends Model
{
    use HasFactory;
    protected $guarded = [];
}

app/Http/Controllers/Superadmin/AdminController.php
<?php

namespace App\Http\Controllers\Superadmin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use Illuminate\Support\Facades\Http;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\Collection;
use Illuminate\Pagination\LengthAwarePaginator;

class AdminController extends Controller
{
    public function index()
    {
        $token = session()->get('tokenlogin');
        $response = Http::withHeaders([
            'Authorization' => 'JWT ' . $token['access_token'],
        ])->get('https://api-ekiosk.bisaai.id:8081/ekiosk_dev/admin/get_user?is_delete=0');
        $data =  json_decode($response->body(), true)['data'];
        $admins = $this->paginate($data);
        $admins->withPath(route('superadmin.admin.index'));
        return view('superadmin.admin.index', compact('admins'));
    }

    public function paginate($items, $perPage = 5, $page = null, $options = [])
    {
        $page = $page ?: (Paginator::resolveCurrentPage() ?: 1);
        $items = $items instanceof Collection ? $items : Collection::make($items);
        return new LengthAwarePaginator($items->forPage($page, $perPage), $items->count(), $perPage, $page, $options);
    }

    public function create()
    {
        return view('superadmin.admin.create');
    }
    public function store(Request $request)
    {
        $token = session()->get('tokenlogin');
        $response = Http::withHeaders([
            'Authorization' => 'JWT ' . $token['access_token'],
        ])->post('https://api-ekiosk.bisaai.id:8081/ekiosk_dev/admin/insert_user', [
            'nama_user' => $request->name,
            'username' => $request->username,
            'password' => $request->password,
            'role' => $request->role,
        ]);
        if ($response->status() == 200) {
            return redirect()->route('superadmin.admin.index')->with('success', 'Data berhasil ditambahkan');
        } else {
            return redirect()->route('superadmin.admin.index')->with('alert', 'Data gagal ditambahkan');
        }
    }

    public function edit($id)
    {
        $token = session()->get('tokenlogin');
        $response = Http::withHeaders([
            'Authorization' => 'JWT ' . $token['access_token'],
        ])->get('https://api-ekiosk.bisaai.id:8081/ekiosk_dev/admin/get_user?id_user=' . $id);
        $data =  json_decode($response->body(), true)['data'][0];
        return view('superadmin.admin.edit', ["user" => $data]);
    }
    public function update(Request $request)
    {
        $token = session()->get('tokenlogin');
        $response = Http::withHeaders([
            'Authorization' => 'JWT ' . $token['access_token'],
        ])->get('https://api-ekiosk.bisaai.id:8081/ekiosk_dev/admin/get_user?id_user=' . $request->id);
        $data =  json_decode($response->body(), true)['data'][0];

        $response = Http::withHeaders([
            'Authorization' => 'JWT ' . $token['access_token'],
        ])->put('https://api-ekiosk.bisaai.id:8081/ekiosk_dev/admin/update_user', [
            'id_user' => $request->id,
            'username' => $request->username,
            'password' => $request->password ? $request->password : $data['password'],
            'role' => $request->role,
        ]);

        if ($response->status() == 200) {
            return redirect()->route('superadmin.admin.index')->with('success', 'Data berhasil diubah');
        } else {
            return redirect()->route('superadmin.admin.index')->with('alert', 'Data gagal diubah');
        }
    }

    public function delete(Request $request)
    {
        $token = session()->get('tokenlogin');
        $response = Http::withHeaders([
            'Authorization' => 'JWT ' . $token['access_token'],
        ])->put('https://api-ekiosk.bisaai.id:8081/ekiosk_dev/admin/update_user', [
            'id_user' => $request->id,
            'is_delete' => 1,
        ]);
        if ($response->status() == 200) {
            return redirect()->route('superadmin.admin.index')->with('success', 'Data berhasil dihapus');
        } else {
            return redirect()->route('superadmin.admin.index')->with('alert', 'Data gagal dihapus');
        }
    }
}

app/Http/Controllers/Superadmin/CategoryController.php
<?php

namespace App\Http\Controllers\Superadmin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use Illuminate\Support\Facades\Http;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\Collection;
use Illuminate\Pagination\LengthAwarePaginator;

class CategoryController extends Controller
{
    public function index()
    {
        $token = session()->get('tokenlogin');
        $response = Http::withHeaders([
            'Authorization' => 'JWT ' . $token['access_token'],
        ])->get('https://api-ekiosk.bisaai.id:8081/ekiosk_dev/kantin/list_kategori?is_delete=0');
        $data =  json_decode($response->body(), true)['data'];
        $categories = $this->paginate($data);
        $categories->withPath(route('superadmin.category.index'));
        return view('superadmin.category.index', compact('categories'));
    }

    public function paginate($items, $perPage = 5, $page = null, $options = [])
    {
        $page = $page ?: (Paginator::resolveCurrentPage() ?: 1);
        $items = $items instanceof Collection ? $items : Collection::make($items);
        return new LengthAwarePaginator($items->forPage($page, $perPage), $items->count(), $perPage, $page, $options);
    }

    public function create()
    {
        return view('superadmin.category.create');
    }
    public function store(Request $request)
    {
        $token = session()->get('tokenlogin');
        $response = Http::withHeaders([
            'Authorization' => 'JWT ' . $token['access_token'],
        ])->post('https://api-ekiosk.bisaai.id:8081/ekiosk_dev/admin/insert_kategori', [
            'nama_kategori' => $request->name,
            'deskripsi_kategori' => $request->description,
            'foto_kategori' => base64_encode(file_get_contents($request->file('image')->getRealPath())),
        ]);
        if ($response->status() == 200) {
            return redirect()->route('superadmin.category.index')->with('success', 'Data berhasil ditambahkan');
        } else {
            $error = json_decode($response->body(), true)['description'];
            return redirect()->route('superadmin.category.index')->with('alert', $error);
        }
    }

    public function edit($id)
    {
        $token = session()->get('tokenlogin');
        $response = Http::withHeaders([
            'Authorization' => 'JWT ' . $token['access_token'],
        ])->get('https://api-ekiosk.bisaai.id:8081/ekiosk_dev/admin/list_kategori?id_kategori=' . $id);
        $data =  json_decode($response->body(), true)['data'][0];
        return view('superadmin.category.edit', ['category' => $data]);
    }
    public function update(Request $request)
    {
        $update = [
            'id_kategori' => $request->id,
            'nama_kategori' => $request->name,
            'deskripsi_kategori' => $request->description,
        ];
        if ($request->image) $update += ['foto_kategori' => base64_encode(file_get_contents($request->file('image')->getRealPath()))];
        $token = session()->get('tokenlogin');
        $response = Http::withHeaders([
            'Authorization' => 'JWT ' . $token['access_token'],
        ])->put('https://api-ekiosk.bisaai.id:8081/ekiosk_dev/admin/update_kategori', $update);

        if ($response->status() == 200) {
            return redirect()->route('superadmin.category.index')->with('success', 'Data berhasil diubah');
        } else {
            $error = json_decode($response->body(), true)['description'];
            return redirect()->route('superadmin.category.index')->with('alert', $error);
        }
    }

    public function delete(Request $request)
    {
        $token = session()->get('tokenlogin');
        $response = Http::withHeaders([
            'Authorization' => 'JWT ' . $token['access_token'],
        ])->put('https://api-ekiosk.bisaai.id:8081/ekiosk_dev/admin/update_kategori', [
            'id_kategori' => $request->id,
            'is_delete' => 1,
        ]);
        if ($response->status() == 200) {
            return redirect()->route('superadmin.category.index')->with('success', 'Data berhasil dihapus');
        } else {
            $error = json_decode($response->body(), true)['description'];
            return redirect()->route('superadmin.category.index')->with('alert', $error);
        }
    }
}

resources/views/superadmin/parking_spot/create.blade.php
@extends('layouts.template')
@section('content')
    <div class="container-fluid">
        @include('component._dashboard_superadmin')
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3 justify-content-between d-flex d-inline">
                <h6 class="m-0 font-weight-bold text-dark"><span class="text-orange-tagar-manual">|</span> Add New Parking
                    Spot</h6>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-6 col-sm-12">
                        <img src="{{ asset('template/img/parking_spot_add.png') }}" style="height:100%;width:100%">
                    </div>
                    <div class="col-lg-6 col-sm-12 my-auto align-items-center">
                        <form action="{{ route('superadmin.parking_spot.store') }}" method="POST"
                            enctype="multipart/form-data">
                            @csrf
                            <div class="form-group ">
                                <label for="client" class="form-label">Client</label>
                                <select name="id_client" id="client" class="form-control" required>
                                    <option value="">~ Pilih ~</option>
                                    @foreach ($clients as $client)
                                        <option value="{{ $client['id_client'] }}">{{ $client['nama_client'] }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group ">
                                <label for="name" class="form-label">Parking Spot Name</label>
                                <input type="text" class="form-control" id="name" name="name" required>
                            </div>
                            <button type="submit" class="btn btn-orange-manual">Add</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        $("#edit").on('show.bs.modal', (e) => {
            var id = $(e.relatedTarget).data('id');
            var name = $(e.relatedTarget).data('name');
            var location = $(e.relatedTarget).data('location');
            var total_transaction = $(e.relatedTarget).data('total_transaction');
            $('#edit').find('input[name="id"]').val(id);
            $('#edit').find('input[name="name"]').val(name);
            $('#edit').find('input[name="location"]').val(location);
            $('#edit').find('input[name="total_transaction"]').val(total_transaction);
        });

        $('#delete').on('show.bs.modal', (e) => {
            var id = $(e.relatedTarget).data('id');
            console.log(id);
            $('#delete').find('input[name="id"]').val(id);
        });
    </script>
@endpush

resources/views/superadmin/parking_spot/edit.blade.php
@extends('layouts.template')
@section('content')
    <div class="container-fluid">
        @include('component._dashboard_superadmin')
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3 justify-content-between d-flex d-inline">
                <h6 class="m-0 font-weight-bold text-dark"><span class="text-orange-tagar-manual">|</span> Add New Parking
                    Spot</h6>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-6 col-sm-12">
                        <img src="{{ asset('template/img/parking_spot_add.png') }}" style="height:100%;width:100%">
                    </div>
                    <div class="col-lg-6 col-sm-12 my-auto align-items-center">
                        <form action="{{ route('superadmin.parking_spot.update') }}" method="POST"
                            enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <input type="hidden" name="id" value="{{ $parkingSpot['id_lokasi_parkir'] }}">
                            <div class="form-group ">
                                <label for="client" class="form-label">Client</label>
                                <select name="id_client" id="client" class="form-control" required>
                                    @forelse($parkingSpot['client'] as $client)
                                        <option value="{{ $client['id_client'] }}"
                                            {{ $client['id_client'] == $parkingSpot['id_client'] ? 'selected' : '' }}>
                                            {{ $client['nama_client'] }}</option>
                                    @empty
                                        <option value="">Client Data Ditemukan</option>
                                    @endforelse
                                </select>
                            </div>
                            <div class="form-group ">
                                <label for="name" class="form-label">Parking Spot Name</label>
                                <input type="text" class="form-control" id="name" name="name"
                                    value="{{ $parkingSpot['nama_lokasi_parkir'] }}" required>
                            </div>
                            <button type="submit" class="btn btn-orange-manual">Update</button>

                            <a href="#" data-id="{{ $parkingSpot['id_lokasi_parkir'] }}" data-toggle="modal"
                                data-target="#delete" class="btn btn-danger btn-sm">Delete</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel"><span class="text-orange-tagar-manual">|</span> Delete
                        Parking Spot</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    Apakah Anda yakin ingin menghapus Data Parking Spot ini?
                </div>
                <div class="modal-footer">
                    <form action="{{ route('superadmin.parking_spot.delete') }}" method="POST"
                        enctype="multipart/form-data">
                        @csrf
                        @method('DELETE')
                        <input type="hidden" name="id">
                        <button class="btn btn-danger btn-sm">Delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        $('#delete').on('show.bs.modal', (e) => {
            var id = $(e.relatedTarget).data('id');
            console.log(id);
            $('#delete').find('input[name="id"]').val(id);
        });
    </script>
@endpush

resources/views/superadmin/parking_spot/index.blade.php
@extends('layouts.template')
@section('content')
    <div class="container-fluid">
        @include('component._dashboard_superadmin')
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3 justify-content-between d-flex d-inline">
                <h6 class="m-0 font-weight-bold text-dark"><span class="text-orange-tagar-manual">|</span> Parking Spot List
                </h6>
                {{-- <a href="{{ route('superadmin.parking_spot.create') }}" class="btn btn-orange-manual">Add New Parking
                    Spot</a> --}}
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Parking Spot</th>
                                <th>Total Transaction</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($parkingSpots as $parking)
                                <tr>
                                    <th>{{ $parking['id_client'] }}</th>
                                    <th>{{ $parking['nama_lokasi_parkir'] }}</th>
                                    <th>{{ $parking['total_transaksi'] }}</th>
                                    <th>
                                        <a href="{{ route('superadmin.parking_spot.edit', $parking['id_lokasi_parkir']) }}"
                                            class="btn btn-warning btn-sm">Edit</a>
                                        <a href="#" data-id="{{ $parking['id_lokasi_parkir'] }}" data-toggle="modal"
                                            data-target="#delete" class="btn btn-danger btn-sm">Delete</a>
                                    </th>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
                <br>
                {{ $parkingSpots->links('pagination::bootstrap-4') }}
            </div>
        </div>
    </div>
    <div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel"><span class="text-orange-tagar-manual">|</span> Delete
                        parkingSpots</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    Apakah Anda yakin ingin menghapus Data Kategori ini?
                </div>
                <div class="modal-footer">
                    <form action="{{ route('superadmin.parking_spot.delete') }}" method="POST"
                        enctype="multipart/form-data">
                        @csrf
                        @method('DELETE')
                        <input type="hidden" name="id">
                        <button class="btn btn-danger btn-sm">Delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        $("#edit").on('show.bs.modal', (e) => {
            var id = $(e.relatedTarget).data('id');
            var name = $(e.relatedTarget).data('name');
            var location = $(e.relatedTarget).data('location');
            var total_transaction = $(e.relatedTarget).data('total_transaction');
            $('#edit').find('input[name="id"]').val(id);
            $('#edit').find('input[name="name"]').val(name);
            $('#edit').find('input[name="location"]').val(location);
            $('#edit').find('input[name="total_transaction"]').val(total_transaction);
        });

        $('#delete').on('show.bs.modal', (e) => {
            var id = $(e.relatedTarget).data('id');
            console.log(id);
            $('#delete').find('input[name="id"]').val(id);
        });
    </script>
@endpush