routes/web.php
<?php

use App\Http\Controllers\Admin\CanteenController;
use App\Http\Controllers\Admin\ClientController;
use App\Http\Controllers\Admin\FoodController;
use App\Http\Controllers\AdminCanteen\OverviewController;
use App\Http\Controllers\AdminCanteen\ProductController;
use App\Http\Controllers\AdminCanteen\ReportController;
use App\Http\Controllers\Superadmin\AdminController;
use App\Http\Controllers\Superadmin\CanteenController as SuperadminCanteenController;
use App\Http\Controllers\Superadmin\CategoryController;
use App\Http\Controllers\Superadmin\ClientController as SuperadminClientController;
use App\Http\Controllers\Superadmin\DashboardController;
use App\Http\Controllers\Superadmin\ParkingSpotController;
use App\Http\Controllers\Superadmin\SmartCanteenController;
use App\Http\Controllers\Superadmin\SmartParkingController;
use App\Http\Controllers\Superadmin\StudentController;
use App\Http\Controllers\Auth\AuthController;

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/', [AuthController::class, 'index']);
Route::get('/login', [AuthController::class, 'index'])->name('login');
Route::post('/login', [AuthController::class, 'store']);
Route::post('/logout', [AuthController::class, 'logout'])->name('logout');

Route::group(['middleware' => ['checkrole:admincanteen']], function () {
    Route::prefix('admin-canteen')->name('admin_canteen.')->group(function () {
        Route::prefix('overview')->name('overview.')->group(function () {
            Route::get('', [OverviewController::class, 'index'])->name('index');
            Route::put('status-canteen', [OverviewController::class, 'statusCanteen'])->name('status_canteen');
        });

        Route::prefix('report')->name('report.')->group(function () {
            Route::get('', [ReportController::class, 'index'])->name('index');
            Route::get('show/{id}', [ReportController::class, 'show'])->name('show');
            Route::get('getPager', [ReportController::class, 'getpager'])->name('get_pager');
            Route::put('updatePager', [ReportController::class, 'updatePager'])->name('update_pager');
            Route::put('updateTaken', [ReportController::class, 'updateTaken'])->name('update_taken');
            Route::put('updateNotif', [ReportController::class, 'updateNotif'])->name('update_notif');
            Route::delete('delete', [ReportController::class, 'delete'])->name('delete');
            // Route::get('cetak-nota/{id}', [ReportController::class, 'print'])->name('print');
        });
        Route::prefix('product')->name('product.')->group(function () {
            Route::get('', [ProductController::class, 'index'])->name('index');
            Route::get('create', [ProductController::class, 'create'])->name('create');
            Route::get('{id}/edit', [ProductController::class, 'edit'])->name('edit');
            Route::post('store', [ProductController::class, 'store'])->name('store');
            Route::get('{id}/edit', [ProductController::class, 'edit'])->name('edit');
            Route::put('update', [ProductController::class, 'update'])->name('update');
            Route::delete('delete', [ProductController::class, 'delete'])->name('delete');
        });
    });
});

//Superadmin
Route::group(['middleware' => ['checkrole:superadmin', 'web']], function () {
    Route::prefix('superadmin')->name('superadmin.')->group(function () {
        Route::prefix('dashboard')->name('dashboard.')->group(function () {
            Route::get('', [DashboardController::class, 'index'])->name('index');
        });

        Route::prefix('admin')->name('admin.')->group(function () {
            Route::get('', [AdminController::class, 'index'])->name('index');
            Route::get('create', [AdminController::class, 'create'])->name('create');
            Route::post('store', [AdminController::class, 'store'])->name('store');
            Route::get('{id}/edit', [AdminController::class, 'edit'])->name('edit');
            Route::put('update', [AdminController::class, 'update'])->name('update');
            Route::delete('delete', [AdminController::class, 'delete'])->name('delete');
        });
        Route::prefix('category')->name('category.')->group(function () {
            Route::get('', [CategoryController::class, 'index'])->name('index');
            Route::get('create', [CategoryController::class, 'create'])->name('create');
            Route::post('store', [CategoryController::class, 'store'])->name('store');
            Route::get('{id}/edit', [CategoryController::class, 'edit'])->name('edit');
            Route::put('update', [CategoryController::class, 'update'])->name('update');
            Route::delete('delete', [CategoryController::class, 'delete'])->name('delete');
        });
        Route::prefix('parking-spot')->name('parking_spot.')->group(function () {
            Route::get('', [ParkingSpotController::class, 'index'])->name('index');
            Route::get('create', [ParkingSpotController::class, 'create'])->name('create');
            Route::post('store', [ParkingSpotController::class, 'store'])->name('store');
            Route::get('{id}/edit', [ParkingSpotController::class, 'edit'])->name('edit');
            Route::put('update', [ParkingSpotController::class, 'update'])->name('update');
            Route::delete('delete', [ParkingSpotController::class, 'delete'])->name('delete');
        });
        Route::prefix('client')->name('client.')->group(function () {
            Route::get('', [SuperadminClientController::class, 'index'])->name('index');
            Route::get('blank', [SuperadminClientController::class, 'blank'])->name('blank');
            Route::get('create', [SuperadminClientController::class, 'create'])->name('create');
            Route::post('store', [SuperadminClientController::class, 'store'])->name('store');
            Route::get('{id}/edit', [SuperadminClientController::class, 'edit'])->name('edit');
            Route::put('update', [SuperadminClientController::class, 'update'])->name('update');
            Route::delete('delete', [SuperadminClientController::class, 'delete'])->name('delete');
        });
        Route::prefix('canteen')->name('canteen.')->group(function () {
            Route::get('', [SuperadminCanteenController::class, 'index'])->name('index');
            Route::get('create', [SuperadminCanteenController::class, 'create'])->name('create');
            Route::post('store', [SuperadminCanteenController::class, 'store'])->name('store');
            Route::get('{id}/edit', [SuperadminCanteenController::class, 'edit'])->name('edit');
            Route::put('update', [SuperadminCanteenController::class, 'update'])->name('update');
            Route::delete('delete', [SuperadminCanteenController::class, 'delete'])->name('delete');
        });

        Route::prefix('user')->name('student.')->group(function () {
            Route::get('', [StudentController::class, 'index'])->name('index');
            Route::get('create', [StudentController::class, 'create'])->name('create');
            Route::post('store', [StudentController::class, 'store'])->name('store');
            Route::get('{id}/edit', [StudentController::class, 'edit'])->name('edit');
            Route::put('update', [StudentController::class, 'update'])->name('update');
            Route::delete('delete', [StudentController::class, 'delete'])->name('delete');
        });

        Route::prefix('smart-canteen')->name('smart_canteen.')->group(function () {
            Route::get('', [SmartCanteenController::class, 'index'])->name('index');
        });
        Route::prefix('smart-parking')->name('smart_parking.')->group(function () {
            Route::get('', [SmartParkingController::class, 'index'])->name('index');
        });
    });
});

resources/views/component/_dashboard_admin_canteen.blade.php
@php
$token = session()->get('tokenlogin');
$id_kantin = session()->get('idkantin');

$response = Http::withHeaders([
    'Authorization' => 'JWT ' . $token['access_token'],
])->get('https://api-ekiosk.bisaai.id:8081/ekiosk_dev/admin/get_order?is_delete=0&id_kantin=' . $id_kantin);
$totalOrders = json_decode($response->body(), true)['row_count'];

$response = Http::withHeaders([
    'Authorization' => 'JWT ' . $token['access_token'],
])->get('https://api-ekiosk.bisaai.id:8081/ekiosk_dev/kantin/list_produk?is_delete=0&id_kantin=' . $id_kantin);
$totalFoods = json_decode($response->body(), true)['row_count'];

$response = Http::withHeaders([
    'Authorization' => 'JWT ' . $token['access_token'],
])->get('https://api-ekiosk.bisaai.id:8081/ekiosk_dev/admin/get_kantin?id_kantin=' . $id_kantin);
$status = json_decode($response->body(), true)['data'][0]['is_aktif'];

$response = Http::withHeaders([
    'Authorization' => 'JWT ' . $token['access_token'],
])->get('https://api-ekiosk.bisaai.id:8081/ekiosk_dev/admin/get_order?is_delete=0&is_rating=1&id_kantin=' . $id_kantin);
$ratings = json_decode($response->body(), true)['data'];

$totalRatings = 0;
for ($i = 0; $i < count($ratings); $i++) {
    $totalRatings += $ratings[$i]['rating'];
}
$totalRatings = $totalRatings / count($ratings);

// $response = Http::withHeaders([
//     'Authorization' => 'JWT ' . $token['access_token'],
// ])->get('https://api-ekiosk.bisaai.id:8081/ekiosk_dev/admin/get_order?is_delete=0&is_status=0');
// $totalTransactionsFailed = json_decode($response->body(), true)['row_count'];

@endphp
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<meta name="csrf-token" content="{{ csrf_token() }}" />

<div class="row">
    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-md font-weight-bold mb-1"><span class="text-orange-tagar-manual">|</span>
                            Total Order</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">{{ $totalOrders ?? '0' }}</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-chart-line fa-2x text-orange-manual"></i>
                    </div>
                </div>
                <small>Number of Total Order</small>
            </div>
        </div>
    </div>

    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-md font-weight-bold mb-1"><span class="text-orange-tagar-manual">|</span>
                            Total Product</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">{{ $totalFoods ?? '0' }}
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-chart-line fa-2x text-orange-manual"></i>
                    </div>
                </div>
                <small>Number of Total Product</small>
            </div>
        </div>
    </div>

    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-md font-weight-bold mb-1"><span class="text-orange-tagar-manual">|</span>
                            Ratings</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">{{ $totalRatings ?? '' }}</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-chart-line fa-2x text-orange-manual"></i>
                    </div>
                </div>
                <small>Number of Average Ratings</small>
            </div>
        </div>
    </div>
    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-md font-weight-bold mb-1"><span class="text-orange-tagar-manual">|</span>
                            Canteen Status</div>
                        <select name="status" id="status" class="form-control">
                            <option value="open" {{ $status == 1 ? 'selected' : '' }}>Open</option>
                            <option value="close" {{ $status == 0 ? 'selected' : '' }}>Close</option>
                        </select>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-chart-line fa-2x text-orange-manual"></i>
                    </div>
                </div>
                <small>Status Canteen Open/Closed</small>
            </div>
        </div>
    </div>
</div>
@push('scripts')
    <script>
        $(document).ready(function() {
            $('#status').on('change', function(e) {
                $value = $(e.currentTarget).val();
                $.ajax({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    },
                    type: 'PUT',
                    url: '{{ route('admin_canteen.overview.status_canteen') }}',
                    dataType: 'json',
                    data: {
                        'status': $value
                    },
                    success: function(data) {
                        alert(data.message);
                    },
                    error: function(data) {
                        alert(data.message);
                    }
                });
            })
        })
    </script>
@endpush

resources/views/component/_dashboard_client.blade.php
@if (request()->is('superadmin/client*'))
    @php
        $url = 'https://api-ekiosk.bisaai.id:8081/ekiosk_dev/admin/get_client?is_delete=0';
    @endphp
@elseif(request()->is('superadmin/parking-spot*'))
    @php
        $url = 'https://api-ekiosk.bisaai.id:8081/ekiosk_dev/admin/get_user?is_delete=0';
    @endphp
@else
    @php
        $url = 'https://api-ekiosk.bisaai.id:8081/ekiosk_dev/admin/get_mahasiswa?is_delete=0';
    @endphp
@endif
@php
$token = session()->get('tokenlogin');
$response = Http::withHeaders([
    'Authorization' => 'JWT ' . $token['access_token'],
])->get($url);
$totalUser = json_decode($response->body(), true)['row_count'];
@endphp
<!-- Content Row -->
<div class="row">


    @if (request()->is('superadmin/client*') ? 'active' : '')
        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-md font-weight-bold mb-1"><span class="text-orange-tagar-manual">|</span>
                                Total Client</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ $totalUser ?? '0' }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-calendar fa-2x text-orange-manual"></i>
                        </div>
                    </div>
                    <small>Number of Client Registered</small>
                </div>
            </div>
        </div>


        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-md font-weight-bold mb-1"><span class="text-orange-tagar-manual">|</span>
                                Add New Client</div>
                            <div class="row">
                                <div class="col-6">
                                    <i class="fas fa-calendar fa-2x text-orange-manual"></i>
                                </div>
                                <div class="col-6">
                                    <a href="{{ route('superadmin.client.blank') }}"
                                        style="border: 1px solid blue;padding:8px;">
                                        <i class="fas fa-plus"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <small>Register a new client</small>
                </div>
            </div>
        </div>
</div>
@elseif(request()->is('superadmin/parking-spot*') ? 'active' : '')
<!-- Earnings (Monthly) Card Example -->
<div class="col-xl-3 col-md-6 mb-4">
    <div class="card shadow h-100 py-2">
        <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                    <div class="text-md font-weight-bold mb-1"><span class="text-orange-tagar-manual">|</span> Total
                        Admin</div>
                    <div class="h5 mb-0 font-weight-bold text-gray-800">{{ $totalUser ?? '0' }}</div>
                </div>
                <div class="col-auto">
                    <i class="fas fa-calendar fa-2x text-orange-manual"></i>
                </div>
            </div>
            <small>Number of Admin Registered</small>
        </div>
    </div>
</div>


<!-- Earnings (Monthly) Card Example -->
<div class="col-xl-3 col-md-6 mb-4">
    <div class="card shadow h-100 py-2">
        <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                    <div class="text-md font-weight-bold mb-1"><span class="text-orange-tagar-manual">|</span> Add New
                        Admin</div>
                    <div class="row">
                        <div class="col-6">
                            <i class="fas fa-calendar fa-2x text-orange-manual"></i>
                        </div>
                        <div class="col-6">
                            <a href="{{ route('superadmin.admin.blank') }}"
                                style="border: 1px solid blue;padding:8px;">
                                <i class="fas fa-plus"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <small>Register a new admin</small>
        </div>
    </div>
</div>
</div>
@else
<!-- Earnings (Monthly) Card Example -->
<div class="col-xl-3 col-md-6 mb-4">
    <div class="card shadow h-100 py-2">
        <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                    <div class="text-md font-weight-bold mb-1"><span class="text-orange-tagar-manual">|</span> Total
                        User</div>
                    <div class="h5 mb-0 font-weight-bold text-gray-800">{{ $totalUser ?? '0' }}</div>
                </div>
                <div class="col-auto">
                    <i class="fas fa-calendar fa-2x text-orange-manual"></i>
                </div>
            </div>
            <small>Number of User Registered</small>
        </div>
    </div>
</div>


<!-- Earnings (Monthly) Card Example -->
<div class="col-xl-3 col-md-6 mb-4">
    <div class="card shadow h-100 py-2">
        <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                    <div class="text-md font-weight-bold mb-1"><span class="text-orange-tagar-manual">|</span> Add New
                        User</div>
                    <div class="row">
                        <div class="col-6">
                            <i class="fas fa-calendar fa-2x text-orange-manual"></i>
                        </div>
                        <div class="col-6">
                            <a href="{{ route('superadmin.user.blank') }}"
                                style="border: 1px solid blue;padding:8px;">
                                <i class="fas fa-plus"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <small>Register a new user</small>
        </div>
    </div>
</div>
</div>
@endif

resources/views/component/_sidebar_admin.blade.php
        <ul class="navbar-nav bg-orange-sidebar sidebar sidebar-dark accordion" id="accordionSidebar">

          <!-- Sidebar - Brand -->
          <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/">
              <div class="sidebar-brand-icon">
                  <i class="fas fa-shopping-cart"></i>
              </div>
              <div class="sidebar-brand-text mx-3">Smart Kiosk <sup>Dashboard</sup></div>
          </a>

          <!-- Divider -->
          <hr class="sidebar-divider">

          <!-- Heading -->
          <div class="sidebar-heading">
              Master Data
          </div>

          
          <li class="nav-item {{ request()->is('superadmin/smart*') ? 'active' : ''  }}">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseZero"
                aria-expanded="true" aria-controls="collapseZero">
                <i class="fas fa-chart-line"></i>
                <span>Overview</span>
            </a>
            <div id="collapseZero" class="collapse 
            {{ request()->is('superadmin/smart**') ? 'show' : ''  }}"
            >
                <div class="bg-white py-2 collapse-inner rounded">
                    <a class="collapse-item {{ request()->is('superadmin/smart-canteen*') ? 'active' : ''  }}" href="{{ route('superadmin.smart_canteen.index') }}">Smart Canteen</a>
                    <a class="collapse-item {{ request()->is('superadmin/smart-parking*') ? 'active' : ''  }}" href="{{ route('superadmin.smart_parking.index') }}">Smart Parking</a>
                </div>
            </div>
        </li>
          <li class="nav-item 
          {{-- {{ request()->is('superadmin/canteen*') ? 'active' : ''  || request()->is('superadmin/category*') ? 'active' : ''  }} --}}
          ">
              <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                  aria-expanded="true" aria-controls="collapseTwo">
                  <i class="fas fa-chart-line"></i>
                  <span>Canteen</span>
              </a>
              <div id="collapseTwo" class="collapse 
              {{-- {{ request()->is('superadmin/canteen*') ? 'show' : ''  || request()->is('superadmin/category*') ? 'show' : ''  }} --}}
              ">
                  <div class="bg-white py-2 collapse-inner rounded">
                      <a class="collapse-item {{ request()->is('superadmin/canteen') ? 'active' : ''  }}" href="{{ route('superadmin.canteen.index') }}">Canteen List</a>
                      <a class="collapse-item {{ request()->is('superadmin/canteen/create') ? 'active' : ''  }}" href="{{ route('superadmin.canteen.create') }}">Add New Canteen</a>
                      <a class="collapse-item {{ request()->is('superadmin/category*') ? 'active' : ''  }} {{ request()->is('superadmin/categories*') ? 'active' : ''  }}" href="{{ route('superadmin.category.index') }}">Categories</a>
                  </div>
              </div>
          </li>
          <li class="nav-item {{ request()->is('superadmin/parking-spot*') ? 'active' : ''  }}">
              <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseThree"
                  aria-expanded="true" aria-controls="collapseThree">
                  <i class="fas fa-chart-line"></i>
                  <span>Parking</span>
              </a>
              <div id="collapseThree" class="collapse 
              {{-- {{ request()->is('superadmin/parking-spot*') ? 'show' : ''  }} --}}
              ">
                  <div class="bg-white py-2 collapse-inner rounded">
                      <a class="collapse-item {{ request()->is('superadmin/parking-spot') ? 'active' : ''  }}" href="{{ route('superadmin.parking_spot.index') }}">Parking Spot</a>
                      <a class="collapse-item {{ request()->is('superadmin/parking-spot/create') ? 'active' : ''  }}" href="{{ route('superadmin.parking_spot.create') }}">Add New Parking</a>
                  </div>
              </div>
          </li>
          <li class="nav-item 
          {{-- {{ request()->is('superadmin/client*') ? 'active' : '' || request()->is('superadmin/admin*') ? 'active' : '' || request()->is('superadmin/user*') ? 'active' : ''  }} --}}
          ">
              <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseFour"
                  aria-expanded="true" aria-controls="collapseFour">
                  <i class="fas fa-chart-line"></i>
                  <span>Superadmin</span>
              </a>
              <div id="collapseFour" class="collapse 
              {{-- {{ request()->is('superadmin/client*') ? 'show' : '' || request()->is('superadmin/admin*') ? 'show' : '' || request()->is('superadmin/user*') ? 'show' : ''  }} --}}
              ">
                  <div class="bg-white py-2 collapse-inner rounded">
                      <a class="collapse-item {{ request()->is('superadmin/client') ? 'active' : ''  }}" href="{{ route('superadmin.client.index') }}">Add New Client</a>
                      <a class="collapse-item {{ request()->is('superadmin/admin') ? 'active' : ''  }}" href="{{ route('superadmin.admin.index') }}">Add New Admin</a>
                      <a class="collapse-item {{ request()->is('superadmin/user') ? 'active' : ''  }}" href="{{ route('superadmin.student.index') }}">Add New User</a>
                  </div>
              </div>
          </li>

      </ul>

resources/views/component/_sidebar_admin_canteen.blade.php
        <ul class="navbar-nav bg-orange-sidebar sidebar sidebar-dark accordion" id="accordionSidebar">

          <!-- Sidebar - Brand -->
          <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/">
              <div class="sidebar-brand-icon">
                  <i class="fas fa-shopping-cart"></i>
              </div>
              <div class="sidebar-brand-text mx-3">Smart Kiosk <sup>Dashboard</sup></div>
          </a>

          <!-- Divider -->
          <hr class="sidebar-divider my-0">

          
          <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseZero"
                aria-expanded="true" aria-controls="collapseZero">
                <i class="fas fa-chart-line"></i>
                <span>Canteen</span>
            </a>
            <div id="collapseZero" class="collapse ">
                <div class="bg-white py-2 collapse-inner rounded">
                    <a class="collapse-item {{ request()->is('admin-canteen/overview*') ? 'active' : ''  }}" href="{{ route('admin_canteen.overview.index') }}">Overview</a>
                    <a class="collapse-item {{ request()->is('admin-canteen/product*') ? 'active' : ''  }}" href="{{ route('admin_canteen.product.create') }}">Add Product</a>
                    {{-- <a class="collapse-item {{ request()->is('admin-canteen/transaction*') ? 'active' : ''  }}" href="{{ route('admin_canteen.transaction.index') }}">Orders</a> --}}
                    <a class="collapse-item {{ request()->is('admin-canteen/report*') ? 'active' : ''  }}" href="{{ route('admin_canteen.report.index') }}">Orders</a>
                </div>
            </div>
        </li>

      </ul>

resources/views/component/_sidebar_rs.blade.php
<style>
  li.active * {
    color: black !important;
    font-weight: bold !important;
  }
</style>
    <div class="sidebar" data-color="dark">
        <!--
        Tip 1: You can change the color of the fdebar using: data-color="blue | green | orange | red | yellow"
        -->
      <div class="logo">
        <a href="/" class="text-white logo-mini">
        </a>
        <a href="/" class="text-white logo-normal"> 
          Aplikasi Ulaweng
        </a>
      </div>
      <div class="sidebar-wrapper" id="sidebar-wrapper">
        <ul class="nav">
          <li class="{{ request()->is('rs/dashboard*') ? 'active' : ''  }}">
            <a href="{{ route('rs.dashboard.index') }}">
              <i class="now-ui-icons design_app"></i>
              <p>Dashboard</p>
            </a>
          </li>

          <li class="{{ request()->is('rs/tren*') ? 'active' : ''  }}">
            <a href="{{ route('rs.tren_pelayanan.hak_kelas_kns.index') }}">
              <i class="now-ui-icons tech_mobile"></i>
              <p>Tren Pelayanan</p>
            </a>
          </li>
          <li class="{{ request()->is('rs/k-kns*') ? 'active' : ''  }}">
            <a href="{{ route('rs.kronis_kns.index') }}">
              <i class="now-ui-icons tech_mobile"></i>
              <p>Pasien Kronis</p>
            </a>
          </li>
          <li class="{{ request()->is('rs/d-kns?level=normal*') ? 'active' : ''  }}">
            <a href="{{ route('rs.diagnosa_kns.index', 'level=normal') }}">
              <i class="now-ui-icons tech_mobile"></i>
              <p>Diagnosa KNS</p>
            </a>
          </li>
          
          <li class="{{ request()->is('rs/d-kns?level=tertinggi*') ? 'active' : ''  }}">
            <a href="{{ route('rs.diagnosa_kns.index', 'level=tertinggi') }}">
              <i class="now-ui-icons tech_mobile"></i>
              <p>Diagnosa Tertinggi</p>
            </a>
          </li>
          
          <li class="{{ request()->is('rs/d-kns?level=terbanyak*') ? 'active' : ''  }}">
            <a href="{{ route('rs.diagnosa_kns.index', 'level=terbanyak') }}">
              <i class="now-ui-icons tech_mobile"></i>
              <p>Diagnosa Terbanyak</p>
            </a>
          </li>
          
          <li class="{{ request()->is('rs/ina-kns*') ? 'active' : ''  }}">
            <a href="{{ route('rs.inacbgs_kns.index') }}">
              <i class="now-ui-icons tech_mobile"></i>
              <p>Inacbgs Tertinggi</p>
            </a>
          </li>
        </ul>
      </div>
    </div>